# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3GXRGPAimIqs9bWg5lC81vN9fSFPi4M
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
path = "drive/My Drive/cln_HCMST2009.dta"
df = pd.io.stata.read_stata(path)

df.head(2)

df.columns.values

caseid_new = df["caseid_new"]

caseid_new.head()

weight1 = df["weight1"]

weight = df["2weight2"]

age = df[" age"]

ppagecat = df["ppagecat"]

ppagect4 = df[" ppagect4"]

ppeduc = df[" ppeduc"]

ppeducat = df[" ppeducat"]

ppethm = df["ppethm "]

ppgender = df["ppethm "]

pphhhead = df["ppethm "]

pphouseholdsize = df[" pphouseholdsize"]

pphouse = df["ppethm "]

ppincimp = df["ppethm "]

hhinc = df["ppethm "]

ppmarit = df["ppethm "]

ppmsacat = df["ppethm "]

ppreg4 = df[" ppreg4"]

ppreg9  = df["ppreg9 "]

pprent  = df["  pprent "]

ppt01  = df["   ppt01  "]

ppt1317 = df["    ppt1317  "]

ppt18ov  = df["  ppt18ov  "]

ppt25 = df[" ppt25 "]

ppt612 = df[" ppt612 "]

children_in_hh  = df["  children_in_hh "]

ppwork  = df[" ppwork  "]

ppnet    = df["    ppnet    "]

ppq14arace    = df["  ppq14arace  "]

pphispan   = df["   pphispan  "]

pprace_white = df["  pprace_white  "]

pprace_black   = df["  pprace_black   "]

pprace_nativeamerican   = df[" pprace_nativeamerican  "]

pprace_asianindian = df["  pprace_asianindian  "]

pprace_chinese   = df["    pprace_chinese   "]

pprace_filipino  = df["  pprace_filipino   "]

pprace_japanese  = df["   pprace_japanese   "]

pprace_korean  = df[" pprace_korean  "]

pprace_vietnamese  = df["  pprace_vietnamese  "]

pprace_otherasian   = df["  pprace_otherasian   "]

pprace_hawaiian    = df["  pprace_hawaiian    "]

pprace_guamanian  = df["  pprace_guamanian  "]

pprace_samoan   = df[" pprace_samoan "]

pprace_otherpacificislander = df["  pprace_otherpacificislander  "]

pprace_someotherrace  = df["   pprace_someotherrace   "]

papglb_friend      = df["  papglb_friend   "]

pppartyid3      =  df["pppartyid3"]

papevangelical    = df[" papevangelical   "]

papreligion   = df["  papreligion   "]

ppppcmdate_yrmo  = df[" ppppcmdate_yrmo  "]

pppadate_yrmo   = df["   pppadate_yrmo   "]

pphhcomp11_member2_age = df["    pphhcomp11_member2_age    "]

pphhcomp11_member3_age  = df["   pphhcomp11_member3_age   "]

pphhcomp11_member4_age  = df["  pphhcomp11_member4_age "]

pphhcomp11_member5_age   = df["   pphhcomp11_member5_age  "]

pphhcomp11_member6_age   = df["      pphhcomp11_member6_age  "]

pphhcomp11_member7_age = df["  pphhcomp11_member7_age  "]

pphhcomp11_member8_age  = df["    pphhcomp11_member8_age   "]

pphhcomp11_member9_age  = df["    pphhcomp11_member9_age   "]

pphhcomp11_member10_age     = df["  pphhcomp11_member10_age  "]

pphhcomp11_member11_age   = df["     pphhcomp11_member11_age   "]

pphhcomp11_member12_age  = df["       pphhcomp11_member12_age   "]

pphhcomp11_member13_age  = df["   pphhcomp11_member13_age    "]

pphhcomp11_member14_age     = df["    pphhcomp11_member14_age"]

pphhcomp11_member15_age    = df["   pphhcomp11_member15_age   "]

pphhcomp11_member2_gender   = df["   pphhcomp11_member2_gender  "]

pphhcomp11_member3_gender     = df["  pphhcomp11_member3_gender   "]

pphhcomp11_member4_gender    = df["         pphhcomp11_member4_gender "]

pphhcomp11_member5_gender  = df["   pphhcomp11_member5_gender    "]

pphhcomp11_member6_gender     = df["      pphhcomp11_member6_gender   "]

pphhcomp11_member7_gender  = df["   pphhcomp11_member7_gender    "]

pphhcomp11_member8_gender       = df["      pphhcomp11_member8_gender"]

pphhcomp11_member9_gender   = df["    pphhcomp11_member9_gender  "]

pphhcomp11_member10_gender      = df["        pphhcomp11_member10_gender  "]

pphhcomp11_member11_gender   = df["    pphhcomp11_member11_gender    "]

pphhcomp11_member12_gender     = df["        pphhcomp11_member12_gender  "]

pphhcomp11_member13_gender   = df["  pphhcomp11_member13_gender   "]

pphhcomp11_member14_gender       = df["     pphhcomp11_member14_gender  "]

pphhcomp11_member15_gender  = df[" = df["      pphhcomp11_member15_gender"]

pphhcomp11_member2_relationship      = df[" pphhcomp11_member2_relationship  "]

pphhcomp11_member3_relationship     = df[" pphhcomp11_member3_relationship    "]

pphhcomp11_member4_relationship     = df["  pphhcomp11_member4_relationship"]

pphhcomp11_member5_relationship  = df["   pphhcomp11_member5_relationship "]

pphhcomp11_member6_relationship = df[" pphhcomp11_member6_relationship "]

pphhcomp11_member7_relationship    = df[" pphhcomp11_member7_relationship "]

pphhcomp11_member8_relationship     = df["pphhcomp11_member8_relationship  "]

pphhcomp11_member9_relationship    = df["  pphhcomp11_member9_relationship "]

pphhcomp11_member10_relationship     = df["     pphhcomp11_member10_relationship "]

pphhcomp11_member11_relationship      = df["   pphhcomp11_member11_relationship    "]

pphhcomp11_member12_relationship      = df["  pphhcomp11_member12_relationship    "]

pphhcomp11_member13_relationship       = df[" pphhcomp11_member13_relationship     "]

pphhcomp11_member14_relationship   = df["          pphhcomp11_member14_relationship    "]

pphhcomp11_member15_relationship  = df["  pphhcomp11_member15_relationship "]

irb_consent      = df["        irb_consent   "]

weight3          = df["   weight3         "]

weight4  = df["  weight4  "]

weight5      = df["    weight5  "]

weight6    = df["  weight6   "]

weight7      = df["      weight7    "]

weight_couples_coresident  = df["     weight_couples_coresident   "]

hcmst_main_interview_yrmo  = df["          hcmst_main_interview_yrmo     "]

duration        = df["  duration "]

qflag  = df[" qflag   "]

glbstatus  = df[" glbstatus   "]

papglb_status   = df[" papglb_status   "]

recsource  = df["         recsource   "]

s1  = df[" s1 "]

s1a  = df["               s1a    "]

s2 = df[" s2  "]

q3_codes = df["   q3_codes  "]

q4   = df[" q4  "]

q5 = df["   q5  "]

q6a   = df[" q6a   "]

q6b  = df["   q6b    "]

q7a    = df["     q7a    "]

q7b  = df["   q7b  "]

q8a  = df[" q8a   "]

q8b = df["            q8b  "]

q9    = df["q9    "]

q10   = df["  q10   "]

q11  = df["   q11  "]

q12  = df["  q12  "]

q13a    = df[" q13a    "]

q13b    = df["  q13b     "]

q14   = df["  q14    "]

q15a1_compressed  = df["  q15a1_compressed   "]

q16  = df["  q16  "]

q17a = df["  q17a  "]

q17b   = df["q17b   "]

q17c  = df["         q17c   "]

q17d     = df["  q17d     "]

gender_attraction  = df["    gender_attraction"]

q18a_1   = df[" q18a_1   "]

q18a_2    = df[" q18a_2    "]

q18a_3   = df["         q18a_3   "]

q18a_refused    = df["      q18a_refused  "]

q18b_codes     = df["  q18b_codes   "]

q18c_codes     = df["  q18c_codes   "]

q19  = df[" q19   "]

q20      = df["     q20   "]

xagemet = df[" xagemet  "]

q21a_refusal  = df["   q21a_refusal"]

ageromantic  = df["  ageromantic  "]

q21b_refusal = df["   q21b_refusal "]

agecohabit = df["    agecohabit    "]

q21c_refusal     = df[" q21c_refusal  "]

agemarry = df[" agemarry  "]

q21d_refusal = df["  q21d_refusal  "]

ageunion     = df["   ageunion    "]

q21e_refusal  = df["             q21e_refusal    "]

q22      = df["q22      "]

q23  = df["  q23    "]

q24_codes    = df[" q24_codes    "]

q25   = df[" q25    "]

q26 = df["  q26   "]

q27  = df["  q27  "]

q28  = df["   q28   "]

q29  = df["  q29  "]

q30  = df["q30  "]

q31_1   = df[" q31_1    "]

q31_2  = df["  q31_2    "]

q31_3  = df["  q31_3  "]

q31_4  = df["  q31_4    "]

q31_5  = df["   q31_5    "]

q31_6  = df["  q31_6    "]

q31_7     = df["      q31_7         "]

q31_8      = df["          q31_8   "]

q31_9  = df["  q31_9    "]

q31_other_text_entered = df[" q31_other_text_entered  "]

q32  = df[" q32  "]

q33_1    = df["    q33_1     "]

q33_2 = df[" q33_2  "]

q33_3    = df["              q33_3   "]

q33_4   = df[" q33_4    "]

q33_5= df[" q33_5 "]

q33_6     = df["  q33_6    "]

q33_7  = df[" q33_7   "]

q33_other_text_entered  = df["  q33_other_text_entered  "]

q34   = df["  q34 "]

q35_codes       = df["           q35_codes  "]

q35_text_entered    = df["  q35_text_entered   "]

metonline     = df["metonline    "]

summary_q24_total     = df["summary_q24_total   "]

q24_r_cowork  = df["  q24_r_cowork   "]

q24_r_friend      = df["     q24_r_friend    "]

q24_r_family    = df[" q24_r_family   "]

q24_r_sig_other   = df["q24_r_sig_other  "]

q24_r_neighbor     = df["  q24_r_neighbor     "]

q24_p_cowork    = df["   q24_p_cowork   "]

q24_p_friend    = df["  q24_p_friend  "]

q24_p_family    = df["q24_p_family   "]

q24_p_sig_other   = df["     q24_p_sig_other "]

q24_p_neighbor      = df[" q24_p_neighbor   "]

q24_btwn_i_cowork    = df["   q24_btwn_i_cowork  "]

q24_btwn_i_friend   = df["     q24_btwn_i_friend "]

q24_btwn_i_family  = df[" q24_btwn_i_family  "]

q24_btwn_i_sig_other    = df[" q24_btwn_i_sig_other "]

q24_btwn_i_neighbor     = df["      q24_btwn_i_neighbor  "]

q24_school     = df["   q24_school    "]

q24_college    = df["  q24_college   "]

q24_military       = df["   q24_military "]

q24_church        = df["    q24_church        "]

q24_vol_org       = df["          q24_vol_org   "]

q24_customer  = df[" q24_customer  "]

metbar     = df[" metbar   "]

q24_internet_dating     = df[" q24_internet_dating  "]

q24_internet_social_networking      = df["           q24_internet_social_networking    "]

q24_internet_game     = df[" q24_internet_game     "]

q24_internet_chat    = df[" q24_internet_chat    "]

q24_internet_community    = df["    q24_internet_community  "]

q24_internet_other   = df["   q24_internet_other"]

q24_public      = df["         q24_public   "]

q24_private_party      = df["      q24_private_party          "]

q24_blind_date    = df["  q24_blind_date "]

q24_vacation       = df["    q24_vacation     "]

q24_singles_service_non_internet = df["      q24_singles_service_non_internet  "]

q24_business_trip     = df["  q24_business_trip     "]

q24_work_neighbor     = df["   q24_work_neighbor "]

q24_fam_sister_active    = df["    q24_fam_sister_active     "]

q24_fam_brother_active      = df[" q24_fam_brother_active  "]

q24_fam_mother_active   = df["       q24_fam_mother_active   "]

q24_fam_father_active  = df["q24_fam_father_active "]

q24_fam_other_active    = df["       q24_fam_other_active    "]

q24_fam_cousins_active        = df[" q24_fam_cousins_active    "]

q24_fam_aunt_niece_active        = df[" q24_fam_aunt_niece_active   "]

q24_fam_uncle_nephew_active       = df["          q24_fam_uncle_nephew_active "]

q24_fam_grandmother_active      = df["     q24_fam_grandmother_active          "]

q24_fam_grandfather_active   = df["          q24_fam_grandfather_active"]

q24_fam_sister_passive     = df["      q24_fam_sister_passive    "]

q24_fam_brother_passive    = df["  q24_fam_brother_passive    "]

q24_fam_mother_passive        = df["   q24_fam_mother_passive    "]

q24_fam_father_passive   = df[" q24_fam_father_passive "]

q24_fam_other_passive    = df["          q24_fam_other_passive"]

q24_fam_cousins_passive    = df[" q24_fam_cousins_passive    "]

q24_fam_aunt_niece_passive      = df["      q24_fam_aunt_niece_passive    "]

q24_fam_uncle_nephew_passive   = df["  q24_fam_uncle_nephew_passive   "]

q24_fam_grandmother_passive    = df["  q24_fam_grandmother_passive    "]

q24_fam_grandfather_passive  = df[" q24_fam_grandfather_passive "]

q24_fam_female    = df["q24_fam_female  "]

q24_fam_male   = df[" q24_fam_male   "]

distancemoved_10mi   = df["   distancemoved_10mi  "]

marrynotreally      = df["   marrynotreally   "]

marrycountry      = df["  marrycountry       "]

civilnotreally  = df["  civilnotreally  "]

partner_deceased       = df["  partner_deceased     "]

partner_religion_reclassified   = df["              partner_religion_reclassified    "]

partner_religion_child_reclass    = df["    partner_religion_child_reclass   "]

own_religion_child_reclass  = df["   own_religion_child_reclass "]

q32_internet        = df["     q32_internet"]

how_met_online    = df["  how_met_online  "]

either_internet   = df["either_internet  "]

either_internet_adjusted   = df["  either_internet_adjusted   "]

same_sex_couple     = df["   same_sex_couple     "]

potential_partner_gender_recodes     = df["            potential_partner_gender_recodes  "]

alt_partner_gender      = df["  alt_partner_gender       "]

how_long_ago_first_met        = df["         how_long_ago_first_met "]

how_long_ago_first_romantic   = df["how_long_ago_first_romantic  "]

how_long_ago_first_cohab      = df["how_long_ago_first_cohab    "]

how_long_ago_first_met_cat     = df["      how_long_ago_first_met_cat        "]

how_long_relationship = df[" how_long_relationship "]

respondent_race     = df["               respondent_race    "]

partner_race          = df[" partner_race          "]

age_difference   = df[" age_difference   "]

met_through_friends  = df["met_through_friends "]

met_through_family     = df["                met_through_family      "]

met_through_as_neighbors    = df[" met_through_as_neighbors    "]

met_through_as_coworkers    = df["   met_through_as_coworkers"]

respondent_religion_at_16   = df["    respondent_religion_at_16   "]

respondent_relig_16_cat        = df["     respondent_relig_16_cat   "]

partner_religion_at_16         = df["        partner_religion_at_16   "]

partner_relig_16_cat  = df[" partner_relig_16_cat  "]

married          = df["   married          "]

parental_approval    = df[" parental_approval    "]

educyr   = df["  educyr  "]

partner_yrsed         = df["     partner_yrsed       "]

home_country_recode   = df["  home_country_recode    "]

us_raised      = df["   us_raised  "]

partner_mom_yrsed      = df["            partner_mom_yrsed          "]

respondent_mom_yrsed = df["              respondent_mom_yrsed  "]

relationship_quality    = df[" relationship_quality  "]

coresident          = df["   coresident      "]

pp2_afterp1         = df["        pp2_afterp1    "]

pp2_pphhhead   = df["  pp2_pphhhead    "]

pp2_pphhsize  = df["pp2_pphhsize  "]

pp2_pphouse     = df["   pp2_pphouse     "]

pp2_ppincimp    = df["        pp2_ppincimp  "]

pp2_ppmarit  = df["     pp2_ppmarit    "]

pp2_ppmsacat  = df["   pp2_ppmsacat    "]

pp2_ppeduc     = df["         pp2_ppeduc          "]

pp2_ppeducat  = df["   pp2_ppeducat "]

pp2_respondent_yrsed    = df["         pp2_respondent_yrsed"]

pp2_ppethm    = df[" pp2_ppethm "]

pp2_ppreg4        = df["      pp2_ppreg4    "]

pp2_ppreg9   = df["  pp2_ppreg9  "]

pp2_pprent  = df["   pp2_pprent   "]

pp2_ppt01      = df["   pp2_ppt01   "]

pp2_ppt1317   = df["    pp2_ppt1317   "]

pp2_ppt18ov = df["    pp2_ppt18ov   "]

pp2_ppt25       = df["pp2_ppt25   "]

pp2_ppt612     = df[" pp2_ppt612  "]

pp2_ppwork      = df["         pp2_ppwork   "]

pp2_ppnet    = df["         pp2_ppnet"]

pp2_ppcmdate_yrmo    = df["    pp2_ppcmdate_yrmo   "]

pp_igdr1 = df["  pp_igdr1  "]

pp_ieduc1     = df["        pp_ieduc1  "]

pp2_igdr2   = df["  pp2_igdr2    "]

pp2_ieduc2   = df["    pp2_ieduc2  "]

w2_deceased        = df["       w2_deceased    "]

w2_multiname      = df["w2_multiname     "]

w2_panelstat       = df["    w2_panelstat "]

w2_donotcontact   = df["    w2_donotcontact"]

w2_assigned   = df["  w2_assigned    "]

w2_f1complete     = df["          w2_f1complete  "]

w2_hcmst_interview_fin_yrmo   = df["  w2_hcmst_interview_fin_yrmo   "]

w2_duration      = df["  w2_duration    "]

w2_xmarry         = df["  w2_xmarry    "]

w2_xss   = df["    w2_xss   "]

w2_source    = df[" w2_source "]

w2_q1  = df["w2_q1 "]

w2_q2   = df["           w2_q2"]

w2_q3    = df[" w2_q3    "]

w2_q4 = df[" w2_q4 "]

w2_q5     = df["       w2_q5     "]

w2_q6  = df["   w2_q6 "]

w2_q7    = df["       w2_q7  "]

w2_q8     = df["      w2_q8"]

w2_q9  = df["   w2_q9    "]

w2_q10  = df[" w2_q10"]

w2_broke_up   = df["     w2_broke_up   "]

w2_days_elapsed = df[" = df[" w2_days_elapsed "]

pp3_pphhhead   = df[" pp3_pphhhead   "]

pp3_pphhsize     = df["  pp3_pphhsize   "]

pp3_pphouse       = df["        pp3_pphouse   "]

pp3_ppincimp    = df["       pp3_ppincimp   "]

pp3_ppmarit   = df["       pp3_ppmarit   "]

pp3_ppmsacat     = df[" pp3_ppmsacat    "]

pp3_pprent  = df[" pp3_pprent  "]

pp3_ppreg4     = df["            pp3_ppreg4    "]

pp3_ppreg9  = df["   pp3_ppreg9    "]

interstate_mover_pp1_pp2    = df["       interstate_mover_pp1_pp2          "]

interstate_mover_pp2_pp3   = df["     interstate_mover_pp2_pp3 "]

interstate_mover_pp1_pp3         = df["      interstate_mover_pp1_pp3  "]

pp3_ppt01    = df[" pp3_ppt01  "]

pp3_ppt1317     = df["   pp3_ppt1317 "]

pp3_ppt18ov     = df["     pp3_ppt18ov"]

pp3_ppt18ov   = df["  pp3_ppt18ov    "]

pp3_ppt25          = df[" pp3_ppt25       "]

pp3_ppt612   = df["pp3_ppt612  "]

pp3_ppwork   = df[" pp3_ppwork  "]

pp3_ppnet   = df["  pp3_ppnet  "]

pp3_ppcmdate_yrmo       = df["        pp3_ppcmdate_yrmo"]

pp3_ppeduc = df[" pp3_ppeduc "]

pp3_ppeducat         = df["           pp3_ppeducat "]

pp3_respondent_yrsed = df[" pp3_respondent_yrsed "]

pp3_ppethm      = df["     pp3_ppethm    "]

pp3_newer   = df["  pp3_newer "]

w2w3_combo_breakup   = df["w2w3_combo_breakup"]

w3_broke_up       = df["        w3_broke_up"]

w3_xpartnered         = df["      w3_xpartnered      "]

w3_xdeceased    = df["             w3_xdeceased    "]

w3_multiname  = df[" w3_multiname  "]

w3_xss     = df["w3_xss  "]

w3_xlast     = df[" w3_xlast   "]

w3_xyear   = df[" w3_xyear  "]

w3_xmonth     = df[" w3_xmonth "]

w3_xqualified     = df["   w3_xqualified    "]

w3_status   = df["        w3_status  "]

w3_complete  = df["  w3_complete "]

w3_source    = df["          w3_source "]

w3_hcmst_interview_fin_yrmo  = df["  w3_hcmst_interview_fin_yrmo "]

w3_days_elapsed  = df["w3_days_elapsed "]

w3_duration  = df["w3_duration "]

w3_xmarry    = df["   w3_xmarry   "]

w3_xtype     = df["  w3_xtype  "]

w3_q1   = df["  w3_q1   "]

w3_q2  = df["   w3_q2    "]

w3_q3 = df[" w3_q3 "]

w3_q4   = df["w3_q4  "]

w3_mbtiming_year = df["w3_mbtiming_year"]

w3_mbtiming_month  = df["   w3_mbtiming_month "]

w3_q5         = df[" w3_q5 "]

w3_q6       = df["                w3_q6     "]

w3_q7   = df["     w3_q7    "]

w3_q8  = df["     w3_q8    "]

w3_q9   = df["  w3_q9    "]

w3_q10   = df["  w3_q10   "]

w3_nonmbtiming_year   = df["    w3_nonmbtiming_year "]

w3_nonmbtiming_month  = df[" w3_nonmbtiming_month  "]

zpnhwhite_cat    = df["   zpnhwhite_cat    "]

zpnhblack_cat      = df["   zpnhblack_cat  "]

zphisp_cat   = df["zphisp_cat  "]

zpmedhhinc_cat    = df["      zpmedhhinc_cat    "]

zpforborn_cat     = df["       zpforborn_cat  "]

zprural_cat       = df["     zprural_cat          "]

q15a1_other_unedited     = df["    q15a1_other_unedited   "]

q15a1    = df[" q15a1 "]

q15a3_codes    = df["   q15a3_codes  "]

w4_xqualified       = df["      w4_xqualified  "]

w4_status   = df["  w4_status   "]

w4_complete = df["  w4_complete  "]

w4_source     = df["          w4_source"]

w4_duration = df["w4_duration"]

w4_hcmst_interview_fin_yrmo  = df[" w4_hcmst_interview_fin_yrmo  "]

w4_xtype       = df["            w4_xtype  "]

w4_xyear  = df["w4_xyear "]

w4_xmonth       = df[" w4_xmonth       "]

w4_xmarry       = df["      w4_xmarry   "]

w4_xlast      = df["   w4_xlast    "]

w4_xwave1_month = df["  w4_xwave1_month  "]

w4_xcivil    = df["  w4_xcivil   "]

w4_xss   = df["  w4_xss   "]

w4_q1    = df[" w4_q1 "]

w4_q2      = df["   w4_q2   "]

w4_quality    = df["         w4_quality    "]

w4_attractive      = df["   w4_attractive        "]

w4_attractive_partner   = df["  w4_attractive_partner   "]

w4_q3   = df["   w4_q3    "]

w4_q4  = df[" w4_q4  "]

w4_mbtiming_year    = df["    w4_mbtiming_year     "]

w4_mbtiming_month    = df["  w4_mbtiming_month  "]

w4_q5   = df["w4_q5 "]

w4_q6  = df[" w4_q6"]

w4_q7      = df["              w4_q7 "]

w4_mar_year   = df[" w4_mar_year   "]

w4_mar_month = df[" w4_mar_month"]

w4_civ_year   = df[" w4_civ_year  "]

w4_q8_a      = df["               w4_q8_a "]

w4_q8_b = df[" w4_q8_b "]

w4_q9     = df["    w4_q9     "]

w4_q10     = df["   w4_q10 "]

w4_nonmbtiming_year       = df["    w4_nonmbtiming_year  "]

w4_nonmbtiming_month    = df["     w4_nonmbtiming_month      "]

w4_nonmbtiming_month      = df["   w4_nonmbtiming_month    "]

xw4_broke_up    = df["xw4_broke_up  "]

w234_combo_breakup     = df["w234_combo_breakup  "]

pp4_ppeduc = df["  pp4_ppeduc  "]

pp4_ppeducat     = df["    pp4_ppeducat  "]

pp4_ppethm    = df["  pp4_ppethm   "]

pp4_pphhhead       = df["             pp4_pphhhead  "]

pp4_pphhsize     = df["  pp4_pphhsize  "]

pp4_pphouse     = df[" pp4_pphouse  "]

pp4_ppincimp    = df["       pp4_ppincimp "]

pp4_ppmarit     = df["    pp4_ppmarit     "]

pp4_ppmsacat      = df["           pp4_ppmsacat   "]

pp4_ppreg4   = df["pp4_ppreg4  "]

pp4_ppreg9     = df["  pp4_ppreg9    "]

pp4_pprent    = df["   pp4_pprent     "]

pp4_ppt01    = df["         pp4_ppt01"]

pp4_ppt25 = df[" pp4_ppt25 "]

pp4_ppt612     = df["      pp4_ppt612 "]

pp4_ppt1317 = df[" pp4_ppt1317"]

pp4_ppt18ov  = df[" pp4_ppt18ov "]

pp4_ppwork = df[" pp4_ppwork "]

pp4_ppnet   = df["     pp4_ppnet "]

pp4_ppcmdate_yrmo   = df["         pp4_ppcmdate_yrmo "]

pp4_newer  = df["pp4_newer"]

ppa2009_services_yrmo  = df["   ppa2009_services_yrmo    "]

ppa2009_how_often_services = df[" ppa2009_how_often_services "]

w5_duration = df["w5_duration "]

w5_source  = df[" w5_source "]

w5_complete= df["w5_complete"]

w5_status  = df["   w5_status   "]

w5x_qualified= df[" w5x_qualified "]

w5x_marry= df["w5x_marry"]

w5x_last= df[" w5x_last"]

w5x_year= df["w5x_year"]

w5x_civil= df[" w5x_civil"]

w5x_month = df["w5x_month"]

w5x_civyear= df[" w5x_civyear"]

w5x_civmonth= df[" w5x_civmonth"]

w5_q1 = df["w5_q1"]

w5_q2= df[" w5_q2"]

w5_sex_frequency = df["w5_sex_frequency"]

w5_p_monogamy = df["w5_p_monogamy"]

w5_identity = df["w5_identity"]

w5_outness= df[" w5_outness"]

w5_q3 = df["w5_q3"]

w5_q4 = df["w5_q4"]

w5_mbtiming_month = df[" w5_mbtiming_month  "]

w5_mbtiming_year   = df[" w5_mbtiming_year   "]

w5_q5     = df["   w5_q5   "]

w5_q6   = df["w5_q6"]

w5_q7 = df["w5_q7"]

w5_mar_year= df[" w5_mar_year"]

w5_mar_month = df["w5_mar_month"]

w5_q8  = df[" w5_q8"]

w5_civ_year = df[" w5_civ_year "]

w5_civ_month  = df[" w5_civ_month "]

w5_q9= df["w5_q9"]

w5_q10= df["w5_q10"]

w5_nonmbtiming_year = df["w5_nonmbtiming_year"]

w5_nonmbtiming_month    = df["        w5_nonmbtiming_month  "]

w5_broke_up       = df["   w5_broke_up          "]

w5_hcmst_interview_fin_yrmo= df["   w5_hcmst_interview_fin_yrmo   "]

w2345_combo_breakup    = df["      w2345_combo_breakup    "]

responded_to_w234or5   = df[" responded_to_w234or5 "]

pp5_ppage      = df["pp5_ppage    "]

pp5_ppagecat        = df["   pp5_ppagecat   "]

pp5_ppagect4    = df[" pp5_ppagect4  "]

pp5_ppeduc   = df["pp5_ppeduc    "]

pp5_ppeducat   = df["    pp5_ppeducat    "]

pp5_ppethm      = df["      pp5_ppethm    "]

pp5_ppgender = df["pp5_ppgender"]

pp5_pphhhead     = df["   pp5_pphhhead   "]

pp5_pphhsize  = df["  pp5_pphhsize   "]

pp5_pphouse  = df["    pp5_pphouse  "]

pp5_ppincimp        = df["        pp5_ppincimp"]

pp5_ppmarit= df["  pp5_ppmarit  "]

pp5_ppcmdate_yrmo = df["pp5_ppcmdate_yrmo"]

pp5_newer       = df["    pp5_newer    "]

pp5_ppmsacat   = df["            pp5_ppmsacat   "]

pp5_ppreg4  = df["   pp5_ppreg4    "]

pp5_ppreg9 = df[" pp5_ppreg9  "]

pp5_pprent      = df["   pp5_pprent     "]

pp5_ppt01  = df["  pp5_ppt01   "]

pp5_ppt25         = df["      pp5_ppt25   "]

pp5_ppt612   = df["  pp5_ppt612    "]

pp5_ppt1317  = df["  pp5_ppt1317    "]

pp5_ppt18ov = df["  pp5_ppt18ov   "]

pp5_ppwork = df["  pp5_ppwork   "]

pp5_ppnet   = df[" pp5_ppnet    "]

ppmarit_2014    = df["            ppmarit_2014   "]

ppcmarit_2014_yrmo = df["    ppcmarit_2014_yrmo  "]

ppmarit_2013     = df["     ppmarit_2013"]

ppcmarit_2013_yrmo   = df["         ppcmarit_2013_yrmo      "]

ppmarit_2012     = df["     ppmarit_2012  "]

ppcmarit_2012_yrmo= df[" ppcmarit_2012_yrmo "]

ppmarit_2011      = df["       ppmarit_2011       "]

ppcmarit_2011_yrmo     = df["  ppcmarit_2011_yrmo   "]

ppmarit_2010      = df["   ppmarit_2010   "]

ppcmarit_2010_yrmo     = df["         ppcmarit_2010_yrmo     "]

ppmarit_2009   = df["   ppmarit_2009   "]

ppcmarit_2009_yrmo     = df["       ppcmarit_2009_yrmo  "]

ppmarit_2007   = df["  ppmarit_2007   "]

ppcmarit_2007_yrmo   = df[" ppcmarit_2007_yrmo "]

male = df["   male "]

educ  = df["  educ  "]

educd1 = df["           educd1    "]

educd2    = df[" educd2    "]

educd3    = df["  educd3   "]

educd4  = df["   educd4   "]

relign = df[" relign  "]

relignd1         = df["        relignd1    "]

relignd2  = df["relignd2  "]

relignd3    = df[" relignd3   "]

relignd4    = df["   relignd4      "]

ethnicd1   = df["ethnicd1 "]

ethnicd2    = df["   ethnicd2    "]

ethnicd3  = df["    ethnicd3  "]

ethnicd4      = df["ethnicd4   "]

ethnicd5   = df[" ethnicd5  "]

gay    = df["   gay  "]

marstat  = df["     marstat   "]

marstatd1   = df["  marstatd1   "]

marstatd2  = df["    marstatd2    "]

marstatd3   = df[" marstatd3  "]

marstatd4= df["  marstatd4 "]

imetonline  = df["  imetonline  "]

metonlinebar= df["metonlinebar"]





